### ISSUE TITLE
Add template aliases

### ISSUE THREAD

**Issue by mlorbetske** [ligershark/mutant-chicken#12]
Thinking something like this:

`dotnet new3 template alias long.name short.name`
## Impact to `dotnet new3 template list [pattern]`

This should write another configuration file that maps the long name to the short name. Templates with aliases should show up at the bottom of the template list (for improved discoverability) and should show the alias in parenthesis next to the full name.

Patterns should also search in aliases, descriptions and authors.
## Impact to `dotnet new3 [name]`

Aliases should be accepted in the name parameter position
## Aliases and short names should show in the template list

ex.

```
Templates                  Id         Alias
- My Very Cool Template    [mvc]      m
```

**Comment by mlorbetske** [comment]
@sayedihashimi in talking with @davidfowl earlier today, it sounds like we should add aliases (for now because VS template IDs aren't memorable/are too long, in the future for frequently used templates) - what do you think of my plan?

**Comment by sayedihashimi** [comment]
@mlorbetske I think what you are proposing here sounds good. The filtering is good, but having an explicit alias is nice as well.
