### ISSUE TITLE
Rename all the projects to something usable

### ISSUE THREAD

**Issue by mlorbetske** [ligershark/mutant-chicken#16]
Also, come up with the name to use

**Comment by sayedihashimi** [comment]
@mlorbetske when would be a good time to do this? I can make the changes, but don't want to run into any merge conflicts so we should coordinate.

**Comment by mlorbetske** [comment]
@sayedihashimi  I can do this if we have the name, this may break quite a few things so we'll need to make sure things are clean before beginning. What name should we use?
