### ISSUE TITLE
Improve output of dotnet new3 source list

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#19]
Improve output of dotnet new3 source list.

Sayed will come up with a proposal here.

```
>dotnet new3 source list
Alias - Provider - Location
VSProj - FileSystem - C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates
```

**Comment by mlorbetske** [comment]
This command has been removed, `-c|--current-config` formats the outputs of all sources/components as nice tables
