### ISSUE TITLE
Get build on Linux/Mac working

### ISSUE THREAD

**Issue by mlorbetske** [ligershark/mutant-chicken#27]
Add more RIDs to `dotnet-new3`
Get builds for the CLI for the different environments we want working & wired up with CI

**Comment by mlorbetske** [comment]
@sayedihashimi do we want x-plat for the demo or is win10-x64 fine for now? If we want x-plat pull this back to the demo milestone and let's get someone to do it

**Comment by mlorbetske** [comment]
Thinking of giving this to @samratsaha, @sayedihashimi any thoughts?

**Comment by sayedihashimi** [comment]
We can't accept external contributions until we move into a MSFT repo but it's a wonderful idea

**Comment by samratsaha** [comment]
No worries. Will play around a bit, so can help out when/if it opens up.
Looks like fun. Thanks guys!

Principal BlueCity LLC
Website: bluecityllc.com
Linkedin: Company https://www.linkedin.com/company/bluecity-llc , ​​
Personal http://www.linkedin.com/pub/samrat-saha/23/966/319/

**Comment by mlorbetske** [comment]
Ubuntu 14.04/16.04 is working

**Comment by sayedihashimi** [comment]
Sweet 🍬

**Comment by mlorbetske** [comment]
With the Ubuntu build working for dotnet-new3 and the move to treating this as a portable dependency of the CLI, x-plat build itself isn't as an important of an item anymore (and we'll get build verification for free after doing #57).

**Comment by samratsaha** [comment]
Sending out of caution- You may get duplicate emails vis-a-vis this matter,
informing all contacts to make sure everyone is notified.

Principal BlueCity LLC
Website: bluecityllc.com
Linkedin: Company <https://www.linkedin.com/company/bluecity-llc> , ​​
Personal <http://www.linkedin.com/pub/samrat-saha/23/966/319/>
