### ISSUE TITLE
Default editor in VS

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#28]
When I open the `.netnew.config` file in VS the JSON editor is not used by default. Can we fix this?

**Comment by mlorbetske** [comment]
@sayedihashimi we'd need some extra magic - the XML editor is hooking everything with the .config extension, might just change the file name to `.netnew.json` to fix it

**Comment by mlorbetske** [comment]
When you get latest, use `.netnew.json` instead of `.netnew.config`

**Comment by sayedihashimi** [comment]
ok sounds good, thanks.
