### ISSUE TITLE
Add Regex Replace macro for runnable project configs

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#29]
In VS when I create a project named `Mvc-App01` the namespace value is `Mvc_App01`. When using the template @mlorbetske provided for a runnable project after updating the config the resulting project has a namespace of `Mvc-App01`

**Comment by mlorbetske** [comment]
@sayedihashimi for vstemplates there's an issue for this already, for runnable projects a new macro will be required.

**Comment by sayedihashimi** [comment]
@mlorbetske ok should we use this to trace the macro for runnable projects?

**Comment by mlorbetske** [comment]
@sayedihashimi Yep, let's rename to "regex replace macro" - it'll process a parameter or variable and run a regex replacement on it, storing it as a new variable

**Comment by mlorbetske** [comment]
The vstemplate side is #14
