### ISSUE TITLE
Simplify adding a source

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#31]
The command to add a new source is

```
dotnet new3 source add <sourcename> <sourcepath>
```

I'm not sure what's the syntax for adding a NuGet package is currently here, but I'm guessing the following.

```
dotnet new3 source add <sourcename> <sourceversion>
```

From https://github.com/dotnet/cli/issues/2052, the proposal is

```
dotnet new --install <sourcename> <sourceversion>
```

In `dotnet new3` the user has to remember two items `source` and `add`. Can we reduce to one single item, perhaps `add` or `install`.

**Comment by mlorbetske** [comment]
I like that, we can get rid of `component` too this way, one `--install` to rule them all

**Comment by mlorbetske** [comment]
Let's add --uninstall and something for listing what's installed too. We can use this to get rid of source and component commands, which will make help work better

**Comment by sayedihashimi** [comment]
> Let's add --uninstall and something for listing what's installed too. We can use this to get rid of source and component commands, which will make help work better

Sounds good

**Comment by mlorbetske** [comment]
`-i|--install`, `-u|--uninstall` and `-c|--current-config` now work with either sources or components, no additional name parameters are required, multiple components or sources can be installed/uninstalled at once.
