### ISSUE TITLE
Simplify listing templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#32]
Here is the command to list templates.

```
dotnet new3 template list
```

From https://github.com/dotnet/cli/issues/2052 the proposed command was 

```
dotnet new --list
```

Can we simplify `template list` here?

**Comment by mlorbetske** [comment]
@sayedihashimi `dotnet new3 -l` also lists

**Comment by sayedihashimi** [comment]
Thanks, that is good closed it

**Comment by mlorbetske** [comment]
@sayedihashimi I'm inclined to remove the template command entirely, if you agree, let's reopen this and track that here, I think it just adds confusion having it there at this point.
