### ISSUE TITLE
Improve output of list

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#33]
Here is the output from list

```
>dotnet new3 --list
Template Name - Source Name - Generator Name
SayedMvc - Foo - Runnable Project
Basic MVC App 42 - Foo - Runnable Project
```

The [proposal](https://github.com/dotnet/cli/issues/2052) contains

```
~/code> dotnet new --list

MS.DotNetCore.New.Templates 1.0.0
  - Console Application    [console]
  - Class Library          [classlib]
```

This is much easier to read.

Our current default output can be improved in the following ways.
- Text vertical alignment
- Hide source and generator name by default. We can add a command line option(s) for those who are interested.

Currently I'm testing with folder based templates. I'd like to see the output for a nuget package template as well.

**Comment by mlorbetske** [comment]
@sayedihashimi putting the template in a zip will show that style of output too (identical to a nupkg). Let's add, short name to templates and align this to the aliases proposal as well, should be easy to change.

**Comment by sayedihashimi** [comment]
@mlorbetske ok sounds good.

**Comment by mlorbetske** [comment]
List outputs are now configurable, padded tables, leaving this open because we don't have a short name option yet

**Comment by mlorbetske** [comment]
Moving the alias updates to #12
