### ISSUE TITLE
Improve default output when multiple templates match

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#34]
When starting template creation, if multiple template names match here is the default output.

```
>dotnet new3 WinRT.UAP
No template with name "WinRT.UAP" was found in any of the configured sources, searching...
8 matching template(s) found.
Template Name - Source Name - Generator Name
[0] Microsoft.CS.WinRT.UAP.BlankApplication - VSProj - VS Templates
[1] Microsoft.CS.WinRT.UAP.ClassLibrary - VSProj - VS Templates
[2] Microsoft.CS.WinRT.UAP.RuntimeComponent - VSProj - VS Templates
[3] Microsoft.CPP.WinRT.UAP.BlankApp - VSProj - VS Templates
[4] Microsoft.CPP.WinRT.UAP.UnitTest - VSProj - VS Templates
[5] Microsoft.VB.WinRT.UAP.BlankApplication - VSProj - VS Templates
[6] Microsoft.VB.WinRT.UAP.ClassLibrary - VSProj - VS Templates
[7] Microsoft.VB.WinRT.UAP.RuntimeComponent - VSProj - VS Templates
Template # [0 - 7] (q to cancel):
1
```

The [proposal](https://github.com/dotnet/cli/issues/2052) contains

```
 > dotnet new

  Templates
  -----------------------------------
  1. Console Application [console]
  2. Class Library       [classlib]
  3. ASP.NET Core        [aspnetcore]

Select a template [1]: 1
```

This is easier to read than what we have today. I think we can remove the message about no exact match found.

**Comment by mlorbetske** [comment]
@sayedihashimi this will be an issue with vstemplates (all the nice metadata lives outside of the template file), lets move this to RTM and skip the vstemplate stuff for the demo.

**Comment by mlorbetske** [comment]
@sayedihashimi the vstemplate part I mean, the listing formats/entry points and shortnames for runnable projects can stay

**Comment by mlorbetske** [comment]
@sayedihashimi also, I thought you wanted arrow navigation in these - should we do that or the numeric selections?

**Comment by sayedihashimi** [comment]
@mlorbetske ok on moving vstemplate to RTM.

> also, I thought you wanted arrow navigation in these - should we do that or the numeric selections?

I think the ideal is some combo of numbers + up/down + paging. For the demo/rtm lets just keep numbers.

**Comment by mlorbetske** [comment]
Tracking the inclusion of aliases/shortnames in #12
