### ISSUE TITLE
Modify the "conditional" operation or create a new operation that handles un-prefixing matched blocks

### ISSUE THREAD

**Issue by mlorbetske** [ligershark/mutant-chicken#56]
```
//#if FOO
//Content if FOO was true
//#else
Content if FOO was false
//#endif
```

Should automatically un-comment `Content if FOO was true` when `FOO` is true and should leave `Content if FOO was false` as a literal if `FOO` as not true. The operation will need to buffer the content being written to see if the included block is uniformly commented out (needs a more rigorous definition) before committing it to the output stream.

https://github.com/dotnet/cli/issues/2052#issuecomment-231299842

**Comment by RehanSaeed** [comment]
It has to be noted that the case where the code block contains a comment should also be handled:

```
//#if FOO
// Some comment
int i = 0;
//#else
// // Some comment
// int i = 0
//#endif
```

I do this with the use of a double comment.

**Comment by mlorbetske** [comment]
Current design is:

```
//#if (FOO)
// Some comment
int i = 0;
////#else <-- Note the double comment, this indicates that comment stripping will be done if the block is active
// // Some comment
// int i = 0;
//#endif
```

We'll also change the defaults for languages that don't support preprocessors to use `//#if` instead of `//if` (currently used)

**Comment by RehanSaeed** [comment]
Support for multiple file formats is essential. I use:
- `//` as the default.
- `<!-- -->` for HTML and XML based formats.
- `@* *@` for Razor.
- `#` for text based formats e.g. nginx.conf, robots.txt etc.

**Comment by mlorbetske** [comment]
The work to do the block uncommenting (blocks of line comments that is) was done here https://github.com/ligershark/microsoft-templateengine/pull/69 and updated https://github.com/dotnet/templating/pull/2 (we've moved to https://github.com/dotnet/templating). The work to set the rest of the default commenting styles is being tracked by https://github.com/dotnet/templating/issues/4 in the new repo.

**Comment by seancpeters** [comment]
Conditional handling for windows batch files using "rem" line level comments, was setup in this commit:
https://github.com/dotnet/templating/pull/39/commits/1c0d07898ad1451e95e1f9d118eeb460a6b8ba40

Other commits in the same PR (still in progress) deal with nginx.conf comment processing using "#" line level comments. This is still in progress, but we'll be able to re-use it for other file types using that style of comments.

**Comment by seancpeters** [comment]
The nginx.conf and robots.txt setup is complete with https://github.com/dotnet/templating/pull/39/commits/d33aa93c0963a099f71613fb2def35e9eb58d90e

**Comment by sayedihashimi** [comment]
:shipit:
